apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deploy
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  sources:
    # Chart from Bitnami Helm Repo
    - chart: nginx
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 15.3.2   # Use the desired version
      helm:
        valueFiles:
        - $values/K8_ENV/UAT/nginx_values.yaml

    # Values from Git
    - repoURL: 'https://github.com/Arpit-Sharma-as/devops.git'
      targetRevision: main
      ref: values

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
