replicaCount: 2

image:
  registry: docker.io
  repository: bitnami/nginx
  tag: 1.25.3
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deploy-nginx
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
spec:
  rules:
    - host: nginx.argocd.local  # replace with your actual domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: deploy-nginx
                port:
                  name: http
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  enabled: true

readinessProbe:
  enabled: true
