replicaCount: 2

image:
  registry: docker.io
  repository: bitnami/nginx
  tag: 1.25.3
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hostname: nginx.argocd.local
  path: /
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  tls: false

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  enabled: true

readinessProbe:
  enabled: true
