apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deploy-nginx
  namespace: argocd
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/group.name: "nginx-group"
    alb.ingress.kubernetes.io/success-codes: "200-399"
  labels:
    app.kubernetes.io/instance: deploy
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nginx
    app.kubernetes.io/version: 1.25.2
    helm.sh/chart: nginx-15.3.2
spec:
  ingressClassName: alb
  rules:
  - host: nginx.argocd.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: deploy-nginx
            port:
              name: http
